# general config settings
output_path: "./work_dirs"
print_output_every: 50
num_workers: 4

# dataset settings
dataset_name: 'Quora'
data:
  max_length: 80
  train:
    dataset_length: -1
  val:
    train_test_split: 0.3
    dataset_length: 100

# train settings
train:
  batch_size: 25
  learning_rate: 0.0001
  num_epochs: 1
  batch_size: 32
  accumulation_steps: 1
  weight_decay: 0.01
  epoch_length: 500
  with_amp: False

# model settings
model:
  name: "EDL"
  emb_dim: 512
  emb_hid_dim: 256
  enc_dropout: 0.5
  enc_rnn_dim: 512
  enc_dim: 512
  gen_rnn_dim: 512
  gen_dropout: 0.5
