log_dir: "logs"
save_dir: "save"
gen_dir: "samples"

dataset:
  name: "quora"
  input_ques_h5: "data/quora_dataset/quora_data_prepro.h5"
  input_json: "data/quora_dataset/quora_data_prepro.json"

  train_dataset_len: 1000
  val_dataset_len: 30000

train:
  batch_size: 25
  n_epochs: 1
  learning_rate: 0.0008

model:
  name: "EDLP"
  emb_dim: 512
  emb_hid_dim: 256
  enc_dropout: 0.5
  enc_rnn_dim: 512
  enc_dim: 512
  gen_rnn_dim: 512
  gen_dropout: 0.5
